
train_gens = {"n_parity": 5,
              "n_parity_only_n": 5000,
                   "simple_alu": 10000,
                   "maze_with_stepping_stones": 4000,
                   "locomotion_with_obstacles": 1000,
                   "locomotion": 1*150,
                   "ant": 1*1000,
                "halfcheetah": 1*150,

                   "deceptive_maze_easy": 100,
                   "Acrobot-v1": 200*10,
                   "MountainCar-v0": 200*10,
                   "MountainCarContinuous-v0": 200*15,
                   "CartPole-v1": 200*10,
                   "Breakout-MinAtar": 1000,
                   "Freeway-MinAtar": 3000,
                   "SpaceInvaders-MinAtar": 1000,
                   "Asterix-MinAtar": 1000,
                   "craftax": 1000,
                   "kinetix": 200,
                   }



hyperparams = {
    "n_parity": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
            "kinetix": { "num_layers": 2,
                    "num_hidden": 32,
                    "activation": "tanh",
                    "final_activation": "tanh",
                },
    "n_parity_only_n": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
   "simple_alu": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
    "maze_with_stepping_stones": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
    "locomotion_with_obstacles": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
    "locomotion_old": { "num_layers": 2,
                    "num_hidden": 16,
                    "activation": "relu",
                    "final_activation": "linear",
                },
    ("locomotion", "halfcheetah"): { "num_layers": 2,
                "num_hidden": 4,
                "activation":"tanh",
                "final_activation": "tanh",
            },
    ("halfcheetah"): { "num_layers": 2,
                "num_hidden": 4,
                "activation":"tanh",
                "final_activation": "tanh",
            },
    "deceptive_maze_easy": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
    ("locomotion", "ant"): { "num_layers": 2,
                    "num_hidden": 16,
                    "activation": "tanh",
                    "final_activation": "tanh",
                },
        ( "ant"): { "num_layers": 2,
                    "num_hidden": 16,
                    "activation": "tanh",
                    "final_activation": "tanh",
                },
    "Acrobot-v1": { "num_layers": 2,
                "num_hidden": 16,
                "activation":"relu",
                "final_activation": "linear",
                },
    "MountainCar-v0": { "num_layers": 2,
                "num_hidden": 16,
                "activation":"relu",
                "final_activation": "linear",
                },
    "MountainCarContinuous-v0": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "CartPole-v1": { "num_layers": 2,
                "num_hidden": 16,
                "activation":"relu",
                "final_activation": "linear",
                },
    "Breakout-MinAtar": { "num_layers": 2,
                "num_hidden": 16,
                "activation":"relu",
                "final_activation": "linear",
                },
    "Freeway-MinAtar": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "SpaceInvaders-MinAtar": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "Asterix-MinAtar": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "craftax": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
}


